services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2GB
  server:
    build: .
    environment:
      HOST: db
    ports:
      - "8080:8080"
    restart: always    
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1GB